### PR TITLE
FURNACE-152: Upgrade to javassist 3.22.0-GA

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by lincolnthree** [comment]
My only concern here is that it might conflict with addons that include javassist, since I believe these classes are exported to all addons. Have you also checked the JBoss Modules configurations (Specs) to make sure there is nothing that would cause trouble with this?

**Comment by lincolnthree** [comment]
https://github.com/forge/furnace/tree/master/container/src/main/java/org/jboss/forge/furnace/impl/modules/providers

**Comment by lincolnthree** [comment]
https://github.com/forge/furnace/blob/master/container/src/main/java/org/jboss/forge/furnace/impl/modules/providers/FurnaceContainerSpec.java#L27

**Comment by lincolnthree** [comment]
I think this might break things... but... I don't know for certain.

**Comment by gastaldi** [comment]
@lincolnthree that makes sense. What if I used the maven-shade-plugin to repackage the official javassist?

**Comment by gastaldi** [comment]
I've done some tests and apparently everything is ok now. I'll merge and release an `2.8.0.Alpha1` version as a first step

**Pull request merged**
